name: Linting and Formatting

on:
  pull_request:
    branches:
      - '**'

jobs:
  continuous-integration:
    name: Build and Test .NET App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Docker-Api.csproj

      - name: Build project
        run: dotnet build Docker-Api.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
